<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	__DIR__.'/../../Scheduler/Services/BookingService.php',
	__DIR__.'/../../Scheduler/Services/CalendarService.php',
	__DIR__.'/../../Scheduler/Services/MailChimpService.php',
	__DIR__.'/../../Scheduler/Services/MarkdownService.php',

);